#!/bin/bash
choices="Logout\nPoweroff\nReboot"
chosen=$(echo -e $choices | rofi -dmenu -i -p "Power Menu" -theme ~/.cache/colorer/rofi.rasi)
echo "$chosen"

case "$chosen" in
		Logout) bspc quit ;;
		Poweroff) poweroff ;;
		Reboot) reboot ;; 
esac
