#!/usr/bin/env python3
import gkeepapi
import random
import keyring

keep = gkeepapi.Keep()

username = 'nguyenleluc'
token = keyring.get_password('google-keep-token', username)
keep.resume('nguyenleluc@gmail.com', token)

note = keep.get(
    '1wOyIVBgZ3Lkf3tlExKYXT6Ov2jz9EavrHbevwueehvYYJv9jUZ5KsNIUW1e7JaBmriTc').unchecked
choice = random.choice(note)
print(choice.text)
