#!/bin/bash
 
wpg -R $1
wpg -z $1
wpg --brt $1 25
wpg -s $1

# update pywalfox
/home/nguyenleluc/Applications/Pywalfox/daemon/pywalfox.py update

# remove wal-sample files
find $WALLPPAPER_FOLDER -type f -name *wal_sample.png -delete

# link it to a file
ln -s $1 .config/wall --force
