#!/bin/bash
 
#wpg -z $1
wpg -R $1
wpg -A $1
#wpg --brt $1 25
wpg -s $1

feh --bg-fill $1

# update pywalfox
~/.apps/Pywalfox/daemon/pywalfox.py update

# remove wal-sample files
find $WALLPAPER_FOLDER -type f -name *wal_sample.png -delete

cp $1 ~/.config/wall

# notify
notify-send -i $1 "Wallpaper changed" "to $1"
