#!/bin/bash

# kill other instances
script_name=timemanager
for pid in $(pidof -x $script_name); do
    if [ $pid != $$ ]; then
        kill -9 $pid
		echo "Killed other instance"
    fi
done


while [ true ];
	do
	sleep 20m
	notify-send "time manager" "$(uptime -p)"
	done
